In [12]:
import pandas as pd

file_path = r"C:\Projects\Enterprise AI Analytics Platform for Customer Complaints\complaints.csv"

# Read only first 5 rows
sample = pd.read_csv(file_path, nrows=5)

sample

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID
0,2024-11-21T03:41:12.000Z,Vehicle loan or lease,Loan,Managing the loan or lease,Problem with additional products or services p...,I purchased a vehicle from a company called ca...,NaN,Southwest Acceptance Finance Co,FL,33543,NaN,Web,2024-11-21T03:53:35.000Z,Closed with explanation,No,10866944
1,2025-04-08T00:07:13.000Z,Student loan,Federal student loan servicing,Dealing with your lender or servicer,Don't agree with the fees charged,I recently logged into my Mohela and XXXX acco...,NaN,MOHELA,WA,98058,NaN,Web,2025-04-08T00:17:35.000Z,Closed with explanation,No,12856369
2,2025-04-24T15:23:50.000Z,Student loan,Federal student loan servicing,Dealing with your lender or servicer,Trouble with how payments are being handled,I am in the Public Service Loan Forgiveness Pr...,NaN,MOHELA,OH,431XX,NaN,Web,2025-04-24T16:23:17.000Z,Closed with explanation,No,13160260
3,2025-04-14T13:37:42.000Z,Student loan,Federal student loan servicing,Dealing with your lender or servicer,Need information about your loan balance or lo...,NaN,NaN,MOHELA,FL,33543,Servicemember,Web,2025-04-14T13:50:23.000Z,Closed with explanation,No,12979646
4,2025-04-15T01:29:43.000Z,Student loan,Federal student loan servicing,Incorrect information on your report,Account status incorrect,On XX/XX/scrub> 2025 my credit scored dropped ...,NaN,MOHELA,NY,117XX,NaN,Web,2025-04-15T01:46:59.000Z,Closed with explanation,No,12972549

In [14]:
# Column names
sample.columns.tolist()

['Date received',
 'Product',
 'Sub-product',
 'Issue',
 'Sub-issue',
 'Consumer complaint narrative',
 'Company public response',
 'Company',
 'State',
 'ZIP code',
 'Tags',
 'Submitted via',
 'Date sent to company',
 'Company response to consumer',
 'Timely response?',
 'Complaint ID']

In [16]:
# Data types from sample
sample.dtypes

Date received                    object
Product                          object
Sub-product                      object
Issue                            object
Sub-issue                        object
Consumer complaint narrative     object
Company public response         float64
Company                          object
State                            object
ZIP code                         object
Tags                             object
Submitted via                    object
Date sent to company             object
Company response to consumer     object
Timely response?                 object
Complaint ID                      int64
dtype: object

In [20]:
import pandas as pd

file_path = r"C:\Projects\Enterprise AI Analytics Platform for Customer Complaints\complaints.csv"

df = pd.read_csv(file_path, nrows=10, low_memory=False)

df

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID
0,2024-11-21T03:41:12.000Z,Vehicle loan or lease,Loan,Managing the loan or lease,Problem with additional products or services p...,I purchased a vehicle from a company called ca...,NaN,Southwest Acceptance Finance Co,FL,33543,NaN,Web,2024-11-21T03:53:35.000Z,Closed with explanation,No,10866944
1,2025-04-08T00:07:13.000Z,Student loan,Federal student loan servicing,Dealing with your lender or servicer,Don't agree with the fees charged,I recently logged into my Mohela and XXXX acco...,NaN,MOHELA,WA,98058,NaN,Web,2025-04-08T00:17:35.000Z,Closed with explanation,No,12856369
2,2025-04-24T15:23:50.000Z,Student loan,Federal student loan servicing,Dealing with your lender or servicer,Trouble with how payments are being handled,I am in the Public Service Loan Forgiveness Pr...,NaN,MOHELA,OH,431XX,NaN,Web,2025-04-24T16:23:17.000Z,Closed with explanation,No,13160260
3,2025-04-14T13:37:42.000Z,Student loan,Federal student loan servicing,Dealing with your lender or servicer,Need information about your loan balance or lo...,NaN,NaN,MOHELA,FL,33543,Servicemember,Web,2025-04-14T13:50:23.000Z,Closed with explanation,No,12979646
4,2025-04-15T01:29:43.000Z,Student loan,Federal student loan servicing,Incorrect information on your report,Account status incorrect,On XX/XX/scrub> 2025 my credit scored dropped ...,NaN,MOHELA,NY,117XX,NaN,Web,2025-04-15T01:46:59.000Z,Closed with explanation,No,12972549
5,2025-04-15T03:20:02.000Z,Student loan,Federal student loan servicing,Incorrect information on your report,Account status incorrect,"insufficient notice of payment due, and 90 day...",NaN,MOHELA,MN,554XX,NaN,Web,2025-04-15T03:26:59.000Z,Closed with explanation,No,12989972
6,2025-04-15T13:49:47.000Z,Student loan,Federal student loan servicing,Struggling to repay your loan,"Problem with forgiveness, cancellation, or dis...","On XX/XX/ 2025, I made my XXXX qualifying paym...",NaN,MOHELA,NJ,07631,NaN,Web,2025-04-15T14:05:26.000Z,Closed with explanation,No,13009387
7,2025-04-24T11:21:01.000Z,Student loan,Federal student loan servicing,Dealing with your lender or servicer,Trouble with how payments are being handled,MOHELA Forced Forbearance and Inaccessibility ...,NaN,MOHELA,AR,72034,NaN,Web,2025-04-24T11:26:16.000Z,Closed with explanation,No,13161056
8,2025-04-24T21:39:52.000Z,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Account status incorrect,NaN,NaN,MOHELA,FL,33176,NaN,Web,2025-04-24T21:49:27.000Z,Closed with explanation,No,13152136
9,2025-04-25T16:41:40.000Z,Student loan,Federal student loan servicing,Incorrect information on your report,Account information incorrect,NaN,NaN,MOHELA,NJ,07026,Servicemember,Web,2025-04-25T16:56:12.000Z,Closed with explanation,No,13177499

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Date received                 10 non-null     object
 1   Product                       10 non-null     object
 2   Sub-product                   10 non-null     object
 3   Issue                         10 non-null     object
 4   Sub-issue                     10 non-null     object
 5   Consumer complaint narrative  7 non-null      object
 6   Company public response       0 non-null      float64
 7   Company                       10 non-null     object
 8   State                         10 non-null     object
 9   ZIP code                      10 non-null     object
 10  Tags                          2 non-null      object
 11  Submitted via                 10 non-null     object
 12  Date sent to company          10 non-null     object
 13  Company response to consumer  10 non-null     object
 14  Timely response?              10 non-null     object
 15  Complaint ID                  10 non-null     int64
dtypes: float64(1), int64(1), object(14)
memory usage: 1.4+ KB

In [24]:
df.columns.tolist()

['Date received',
 'Product',
 'Sub-product',
 'Issue',
 'Sub-issue',
 'Consumer complaint narrative',
 'Company public response',
 'Company',
 'State',
 'ZIP code',
 'Tags',
 'Submitted via',
 'Date sent to company',
 'Company response to consumer',
 'Timely response?',
 'Complaint ID']

In [26]:
df.shape

(10, 16)

In [28]:
df.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID
0,2024-11-21T03:41:12.000Z,Vehicle loan or lease,Loan,Managing the loan or lease,Problem with additional products or services p...,I purchased a vehicle from a company called ca...,NaN,Southwest Acceptance Finance Co,FL,33543,NaN,Web,2024-11-21T03:53:35.000Z,Closed with explanation,No,10866944
1,2025-04-08T00:07:13.000Z,Student loan,Federal student loan servicing,Dealing with your lender or servicer,Don't agree with the fees charged,I recently logged into my Mohela and XXXX acco...,NaN,MOHELA,WA,98058,NaN,Web,2025-04-08T00:17:35.000Z,Closed with explanation,No,12856369
2,2025-04-24T15:23:50.000Z,Student loan,Federal student loan servicing,Dealing with your lender or servicer,Trouble with how payments are being handled,I am in the Public Service Loan Forgiveness Pr...,NaN,MOHELA,OH,431XX,NaN,Web,2025-04-24T16:23:17.000Z,Closed with explanation,No,13160260
3,2025-04-14T13:37:42.000Z,Student loan,Federal student loan servicing,Dealing with your lender or servicer,Need information about your loan balance or lo...,NaN,NaN,MOHELA,FL,33543,Servicemember,Web,2025-04-14T13:50:23.000Z,Closed with explanation,No,12979646
4,2025-04-15T01:29:43.000Z,Student loan,Federal student loan servicing,Incorrect information on your report,Account status incorrect,On XX/XX/scrub> 2025 my credit scored dropped ...,NaN,MOHELA,NY,117XX,NaN,Web,2025-04-15T01:46:59.000Z,Closed with explanation,No,12972549

In [30]:
df.tail()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID
5,2025-04-15T03:20:02.000Z,Student loan,Federal student loan servicing,Incorrect information on your report,Account status incorrect,"insufficient notice of payment due, and 90 day...",NaN,MOHELA,MN,554XX,NaN,Web,2025-04-15T03:26:59.000Z,Closed with explanation,No,12989972
6,2025-04-15T13:49:47.000Z,Student loan,Federal student loan servicing,Struggling to repay your loan,"Problem with forgiveness, cancellation, or dis...","On XX/XX/ 2025, I made my XXXX qualifying paym...",NaN,MOHELA,NJ,07631,NaN,Web,2025-04-15T14:05:26.000Z,Closed with explanation,No,13009387
7,2025-04-24T11:21:01.000Z,Student loan,Federal student loan servicing,Dealing with your lender or servicer,Trouble with how payments are being handled,MOHELA Forced Forbearance and Inaccessibility ...,NaN,MOHELA,AR,72034,NaN,Web,2025-04-24T11:26:16.000Z,Closed with explanation,No,13161056
8,2025-04-24T21:39:52.000Z,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Account status incorrect,NaN,NaN,MOHELA,FL,33176,NaN,Web,2025-04-24T21:49:27.000Z,Closed with explanation,No,13152136
9,2025-04-25T16:41:40.000Z,Student loan,Federal student loan servicing,Incorrect information on your report,Account information incorrect,NaN,NaN,MOHELA,NJ,07026,Servicemember,Web,2025-04-25T16:56:12.000Z,Closed with explanation,No,13177499

In [32]:
df.isnull().sum()

Date received                    0
Product                          0
Sub-product                      0
Issue                            0
Sub-issue                        0
Consumer complaint narrative     3
Company public response         10
Company                          0
State                            0
ZIP code                         0
Tags                             8
Submitted via                    0
Date sent to company             0
Company response to consumer     0
Timely response?                 0
Complaint ID                     0
dtype: int64

In [34]:
df["Complaint ID"].duplicated().sum()

0

In [37]:
df.dtypes

Date received                    object
Product                          object
Sub-product                      object
Issue                            object
Sub-issue                        object
Consumer complaint narrative     object
Company public response         float64
Company                          object
State                            object
ZIP code                         object
Tags                             object
Submitted via                    object
Date sent to company             object
Company response to consumer     object
Timely response?                 object
Complaint ID                      int64
dtype: object

In [39]:
df.describe(include="all")

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID
count,10,10,10,10,10,7,0.0,10,10,10,2,10,10,10,10,1.000000e+01
unique,10,3,3,4,7,7,NaN,2,7,9,1,1,10,1,1,NaN
top,2024-11-21T03:41:12.000Z,Student loan,Federal student loan servicing,Dealing with your lender or servicer,Account status incorrect,I purchased a vehicle from a company called ca...,NaN,MOHELA,FL,33543,Servicemember,Web,2024-11-21T03:53:35.000Z,Closed with explanation,No,NaN
freq,1,8,8,4,3,1,NaN,9,3,2,2,10,1,10,10,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.283258e+07
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.990390e+05
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.086694e+07
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.297432e+07
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.299968e+07
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.315823e+07
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.317750e+07

In [41]:
df.nunique()

Date received                   10
Product                          3
Sub-product                      3
Issue                            4
Sub-issue                        7
Consumer complaint narrative     7
Company public response          0
Company                          2
State                            7
ZIP code                         9
Tags                             1
Submitted via                    1
Date sent to company            10
Company response to consumer     1
Timely response?                 1
Complaint ID                    10
dtype: int64

In [43]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage.sort_values(ascending=False)

Company public response         100.0
Tags                             80.0
Consumer complaint narrative     30.0
Date received                     0.0
Product                           0.0
Sub-product                       0.0
Issue                             0.0
Sub-issue                         0.0
Company                           0.0
State                             0.0
ZIP code                          0.0
Submitted via                     0.0
Date sent to company              0.0
Company response to consumer      0.0
Timely response?                  0.0
Complaint ID                      0.0
dtype: float64

In [45]:
df.memory_usage(deep=True)

Index                            132
Date received                    730
Product                          658
Sub-product                      750
Issue                            833
Sub-issue                        884
Consumer complaint narrative    7696
Company public response           80
Company                          575
State                            510
ZIP code                         540
Tags                             380
Submitted via                    520
Date sent to company             730
Company response to consumer     720
Timely response?                 510
Complaint ID                      80
dtype: int64

In [47]:
df.memory_usage(deep=True).sum() / 1024

15.9453125

In [49]:
data_quality = pd.DataFrame({
    "Data Type": df.dtypes,
    "Missing Values": df.isnull().sum(),
    "Missing %": (df.isnull().sum() / len(df)) * 100,
    "Unique Values": df.nunique()
})

data_quality

,Data Type,Missing Values,Missing %,Unique Values
Date received,object,0,0.0,10
Product,object,0,0.0,3
Sub-product,object,0,0.0,3
Issue,object,0,0.0,4
Sub-issue,object,0,0.0,7
Consumer complaint narrative,object,3,30.0,7
Company public response,float64,10,100.0,0
Company,object,0,0.0,2
State,object,0,0.0,7
ZIP code,object,0,0.0,9
Tags,object,8,80.0,1
Submitted via,object,0,0.0,1
Date sent to company,object,0,0.0,10
Company response to consumer,object,0,0.0,1
Timely response?,object,0,0.0,1
Complaint ID,int64,0,0.0,10

In [51]:
# Convert column names to snake_case
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
      .str.replace("-", "_")
      .str.replace("?", "", regex=False)
)

df.columns.tolist()

['date_received',
 'product',
 'sub_product',
 'issue',
 'sub_issue',
 'consumer_complaint_narrative',
 'company_public_response',
 'company',
 'state',
 'zip_code',
 'tags',
 'submitted_via',
 'date_sent_to_company',
 'company_response_to_consumer',
 'timely_response',
 'complaint_id']

In [53]:
df["date_received"] = pd.to_datetime(
    df["date_received"],
    errors="coerce"
)

df["date_sent_to_company"] = pd.to_datetime(
    df["date_sent_to_company"],
    errors="coerce"
)

df[["date_received", "date_sent_to_company"]].dtypes

date_received           datetime64[ns, UTC]
date_sent_to_company    datetime64[ns, UTC]
dtype: object

In [57]:
# Fill missing text fields
text_columns = [
    "consumer_complaint_narrative",
    "company_public_response",
    "tags"
]

for col in text_columns:
    df[col] = df[col].fillna("Not Provided")

In [59]:
df[text_columns].isnull().sum()

consumer_complaint_narrative    0
company_public_response         0
tags                            0
dtype: int64

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   date_received                 10 non-null     datetime64[ns, UTC]
 1   product                       10 non-null     object
 2   sub_product                   10 non-null     object
 3   issue                         10 non-null     object
 4   sub_issue                     10 non-null     object
 5   consumer_complaint_narrative  10 non-null     object
 6   company_public_response       10 non-null     object
 7   company                       10 non-null     object
 8   state                         10 non-null     object
 9   zip_code                      10 non-null     object
 10  tags                          10 non-null     object
 11  submitted_via                 10 non-null     object
 12  date_sent_to_company          10 non-null     datetime64[ns, UTC]
 13  company_response_to_consumer  10 non-null     object
 14  timely_response               10 non-null     object
 15  complaint_id                  10 non-null     int64
dtypes: datetime64[ns, UTC](2), int64(1), object(13)
memory usage: 1.4+ KB

In [63]:
df.isnull().sum()

date_received                   0
product                         0
sub_product                     0
issue                           0
sub_issue                       0
consumer_complaint_narrative    0
company_public_response         0
company                         0
state                           0
zip_code                        0
tags                            0
submitted_via                   0
date_sent_to_company            0
company_response_to_consumer    0
timely_response                 0
complaint_id                    0
dtype: int64

In [65]:
df.head()

,date_received,product,sub_product,issue,sub_issue,consumer_complaint_narrative,company_public_response,company,state,zip_code,tags,submitted_via,date_sent_to_company,company_response_to_consumer,timely_response,complaint_id
0,2024-11-21 03:41:12+00:00,Vehicle loan or lease,Loan,Managing the loan or lease,Problem with additional products or services p...,I purchased a vehicle from a company called ca...,Not Provided,Southwest Acceptance Finance Co,FL,33543,Not Provided,Web,2024-11-21 03:53:35+00:00,Closed with explanation,No,10866944
1,2025-04-08 00:07:13+00:00,Student loan,Federal student loan servicing,Dealing with your lender or servicer,Don't agree with the fees charged,I recently logged into my Mohela and XXXX acco...,Not Provided,MOHELA,WA,98058,Not Provided,Web,2025-04-08 00:17:35+00:00,Closed with explanation,No,12856369
2,2025-04-24 15:23:50+00:00,Student loan,Federal student loan servicing,Dealing with your lender or servicer,Trouble with how payments are being handled,I am in the Public Service Loan Forgiveness Pr...,Not Provided,MOHELA,OH,431XX,Not Provided,Web,2025-04-24 16:23:17+00:00,Closed with explanation,No,13160260
3,2025-04-14 13:37:42+00:00,Student loan,Federal student loan servicing,Dealing with your lender or servicer,Need information about your loan balance or lo...,Not Provided,Not Provided,MOHELA,FL,33543,Servicemember,Web,2025-04-14 13:50:23+00:00,Closed with explanation,No,12979646
4,2025-04-15 01:29:43+00:00,Student loan,Federal student loan servicing,Incorrect information on your report,Account status incorrect,On XX/XX/scrub> 2025 my credit scored dropped ...,Not Provided,MOHELA,NY,117XX,Not Provided,Web,2025-04-15 01:46:59+00:00,Closed with explanation,No,12972549

In [67]:
import pandas as pd
from pathlib import Path

# Project Paths
PROJECT_PATH = Path(r"C:\Projects\Enterprise AI Analytics Platform for Customer Complaints")

RAW_FILE = PROJECT_PATH / "data" / "raw" / "complaints.csv"
OUTPUT_FILE = PROJECT_PATH / "data" / "processed" / "complaints_cleaned.csv"

In [69]:
def clean_chunk(chunk):
    
    # Standardise column names
    chunk.columns = (
        chunk.columns
             .str.strip()
             .str.lower()
             .str.replace(" ", "_")
             .str.replace("-", "_")
             .str.replace("?", "", regex=False)
    )

    # Convert dates
    date_columns = [
        "date_received",
        "date_sent_to_company"
    ]

    for col in date_columns:
        chunk[col] = pd.to_datetime(chunk[col], errors="coerce")

    # Fill missing text values
    text_columns = [
        "consumer_complaint_narrative",
        "company_public_response",
        "tags"
    ]

    for col in text_columns:
        chunk[col] = chunk[col].fillna("Not Provided")

    # Remove duplicate Complaint IDs within the chunk
    chunk.drop_duplicates(subset="complaint_id", inplace=True)

    return chunk

In [77]:
print(RAW_FILE)
print(OUTPUT_FILE)

PASTE_YOUR_REAL_COMPLAINTS_CSV_PATH_HERE
C:\Projects\Enterprise AI Analytics Platform for Customer Complaints\data\processed\complaints_cleaned.csv

In [79]:
from pathlib import Path

print(RAW_FILE.exists())
print(OUTPUT_FILE.parent.exists())

False
False

In [81]:
from pathlib import Path

PROJECT_PATH = Path(r"C:\Projects\Enterprise AI Analytics Platform for Customer Complaints")

RAW_FILE = PROJECT_PATH / "complaints.csv"

# Create processed folder if it doesn't exist
(PROJECT_PATH / "data" / "processed").mkdir(parents=True, exist_ok=True)

OUTPUT_FILE = PROJECT_PATH / "data" / "processed" / "complaints_cleaned.csv"

In [83]:
print(RAW_FILE)
print(RAW_FILE.exists())

print(OUTPUT_FILE)
print(OUTPUT_FILE.parent.exists())

C:\Projects\Enterprise AI Analytics Platform for Customer Complaints\complaints.csv
True
C:\Projects\Enterprise AI Analytics Platform for Customer Complaints\data\processed\complaints_cleaned.csv
True

In [85]:
import pandas as pd
import time

chunksize = 100000
first_chunk = True
total_rows = 0
chunk_number = 0

start_time = time.time()

for chunk in pd.read_csv(
    RAW_FILE,
    chunksize=chunksize,
    low_memory=False
):
    chunk_number += 1

    cleaned_chunk = clean_chunk(chunk)

    cleaned_chunk.to_csv(
        OUTPUT_FILE,
        mode="w" if first_chunk else "a",
        header=first_chunk,
        index=False
    )

    total_rows += len(cleaned_chunk)
    first_chunk = False

    print(f"Chunk {chunk_number} processed | Rows so far: {total_rows:,}")

end_time = time.time()

print("ETL Completed Successfully!")
print(f"Total rows processed: {total_rows:,}")
print(f"Time taken: {(end_time - start_time) / 60:.2f} minutes")

Chunk 1 processed | Rows so far: 93,545
Chunk 2 processed | Rows so far: 193,449
Chunk 3 processed | Rows so far: 293,449
Chunk 4 processed | Rows so far: 393,449
Chunk 5 processed | Rows so far: 493,449
Chunk 6 processed | Rows so far: 593,449
Chunk 7 processed | Rows so far: 693,449
Chunk 8 processed | Rows so far: 793,449
Chunk 9 processed | Rows so far: 893,449
Chunk 10 processed | Rows so far: 993,449
Chunk 11 processed | Rows so far: 1,093,449
Chunk 12 processed | Rows so far: 1,193,449
Chunk 13 processed | Rows so far: 1,293,449
Chunk 14 processed | Rows so far: 1,393,449
Chunk 15 processed | Rows so far: 1,493,449
Chunk 16 processed | Rows so far: 1,593,449
Chunk 17 processed | Rows so far: 1,693,449
Chunk 18 processed | Rows so far: 1,793,449
Chunk 19 processed | Rows so far: 1,893,449
Chunk 20 processed | Rows so far: 1,993,449
Chunk 21 processed | Rows so far: 2,093,449
Chunk 22 processed | Rows so far: 2,193,449
Chunk 23 processed | Rows so far: 2,293,449
Chunk 24 processed | Rows so far: 2,393,449
Chunk 25 processed | Rows so far: 2,493,449
Chunk 26 processed | Rows so far: 2,593,449
Chunk 27 processed | Rows so far: 2,693,449
Chunk 28 processed | Rows so far: 2,793,449
Chunk 29 processed | Rows so far: 2,893,449
Chunk 30 processed | Rows so far: 2,993,449
Chunk 31 processed | Rows so far: 3,093,449
Chunk 32 processed | Rows so far: 3,193,449
Chunk 33 processed | Rows so far: 3,293,449
Chunk 34 processed | Rows so far: 3,393,449
Chunk 35 processed | Rows so far: 3,493,449
Chunk 36 processed | Rows so far: 3,593,449
Chunk 37 processed | Rows so far: 3,693,449
Chunk 38 processed | Rows so far: 3,793,449
Chunk 39 processed | Rows so far: 3,893,449
Chunk 40 processed | Rows so far: 3,993,449
Chunk 41 processed | Rows so far: 4,093,449
Chunk 42 processed | Rows so far: 4,193,449
Chunk 43 processed | Rows so far: 4,293,449
Chunk 44 processed | Rows so far: 4,393,449
Chunk 45 processed | Rows so far: 4,493,449
Chunk 46 processed | Rows so far: 4,593,449
Chunk 47 processed | Rows so far: 4,693,449
Chunk 48 processed | Rows so far: 4,793,449
Chunk 49 processed | Rows so far: 4,893,449
Chunk 50 processed | Rows so far: 4,993,449
Chunk 51 processed | Rows so far: 5,093,449
Chunk 52 processed | Rows so far: 5,193,449
Chunk 53 processed | Rows so far: 5,293,449
Chunk 54 processed | Rows so far: 5,393,449
Chunk 55 processed | Rows so far: 5,493,449
Chunk 56 processed | Rows so far: 5,593,449
Chunk 57 processed | Rows so far: 5,693,449
Chunk 58 processed | Rows so far: 5,793,449
Chunk 59 processed | Rows so far: 5,893,449
Chunk 60 processed | Rows so far: 5,993,449
Chunk 61 processed | Rows so far: 6,093,449
Chunk 62 processed | Rows so far: 6,193,449
Chunk 63 processed | Rows so far: 6,293,449
Chunk 64 processed | Rows so far: 6,393,449
Chunk 65 processed | Rows so far: 6,493,449
Chunk 66 processed | Rows so far: 6,593,449
Chunk 67 processed | Rows so far: 6,693,449
Chunk 68 processed | Rows so far: 6,793,449
Chunk 69 processed | Rows so far: 6,893,449
Chunk 70 processed | Rows so far: 6,993,449
Chunk 71 processed | Rows so far: 7,093,449
Chunk 72 processed | Rows so far: 7,193,449
Chunk 73 processed | Rows so far: 7,293,449
Chunk 74 processed | Rows so far: 7,393,449
Chunk 75 processed | Rows so far: 7,493,449
Chunk 76 processed | Rows so far: 7,593,449
Chunk 77 processed | Rows so far: 7,693,449
Chunk 78 processed | Rows so far: 7,793,449
Chunk 79 processed | Rows so far: 7,893,449
Chunk 80 processed | Rows so far: 7,993,449
Chunk 81 processed | Rows so far: 8,093,449
Chunk 82 processed | Rows so far: 8,193,449
Chunk 83 processed | Rows so far: 8,293,449
Chunk 84 processed | Rows so far: 8,393,449
Chunk 85 processed | Rows so far: 8,493,449
Chunk 86 processed | Rows so far: 8,593,449
Chunk 87 processed | Rows so far: 8,693,449
Chunk 88 processed | Rows so far: 8,793,449
Chunk 89 processed | Rows so far: 8,893,449
Chunk 90 processed | Rows so far: 8,993,449
Chunk 91 processed | Rows so far: 9,093,449
Chunk 92 processed | Rows so far: 9,193,449
Chunk 93 processed | Rows so far: 9,293,449
Chunk 94 processed | Rows so far: 9,393,449
Chunk 95 processed | Rows so far: 9,493,449
Chunk 96 processed | Rows so far: 9,593,449
Chunk 97 processed | Rows so far: 9,693,449
Chunk 98 processed | Rows so far: 9,793,449
Chunk 99 processed | Rows so far: 9,893,449
Chunk 100 processed | Rows so far: 9,993,449
Chunk 101 processed | Rows so far: 10,093,449
Chunk 102 processed | Rows so far: 10,193,449
Chunk 103 processed | Rows so far: 10,293,449
Chunk 104 processed | Rows so far: 10,393,449
Chunk 105 processed | Rows so far: 10,493,449
Chunk 106 processed | Rows so far: 10,593,449
Chunk 107 processed | Rows so far: 10,693,449
Chunk 108 processed | Rows so far: 10,793,449
Chunk 109 processed | Rows so far: 10,893,449
Chunk 110 processed | Rows so far: 10,993,449
Chunk 111 processed | Rows so far: 11,093,449
Chunk 112 processed | Rows so far: 11,193,449
Chunk 113 processed | Rows so far: 11,293,449
Chunk 114 processed | Rows so far: 11,393,449
Chunk 115 processed | Rows so far: 11,493,449
Chunk 116 processed | Rows so far: 11,593,449
Chunk 117 processed | Rows so far: 11,693,449
Chunk 118 processed | Rows so far: 11,793,449
Chunk 119 processed | Rows so far: 11,893,449
Chunk 120 processed | Rows so far: 11,993,449
Chunk 121 processed | Rows so far: 12,093,449
Chunk 122 processed | Rows so far: 12,193,449
Chunk 123 processed | Rows so far: 12,293,449
Chunk 124 processed | Rows so far: 12,393,449
Chunk 125 processed | Rows so far: 12,493,449
Chunk 126 processed | Rows so far: 12,593,449
Chunk 127 processed | Rows so far: 12,693,449
Chunk 128 processed | Rows so far: 12,793,449
Chunk 129 processed | Rows so far: 12,893,449
Chunk 130 processed | Rows so far: 12,993,449
Chunk 131 processed | Rows so far: 13,093,449
Chunk 132 processed | Rows so far: 13,193,449
Chunk 133 processed | Rows so far: 13,293,449
Chunk 134 processed | Rows so far: 13,393,449
Chunk 135 processed | Rows so far: 13,493,449
Chunk 136 processed | Rows so far: 13,593,449
Chunk 137 processed | Rows so far: 13,693,449
Chunk 138 processed | Rows so far: 13,793,449
Chunk 139 processed | Rows so far: 13,893,449
Chunk 140 processed | Rows so far: 13,993,449
Chunk 141 processed | Rows so far: 14,093,449
Chunk 142 processed | Rows so far: 14,193,449
Chunk 143 processed | Rows so far: 14,293,449
Chunk 144 processed | Rows so far: 14,393,449
Chunk 145 processed | Rows so far: 14,493,449
Chunk 146 processed | Rows so far: 14,593,449
Chunk 147 processed | Rows so far: 14,693,449
Chunk 148 processed | Rows so far: 14,793,449
Chunk 149 processed | Rows so far: 14,893,449
Chunk 150 processed | Rows so far: 14,993,449
Chunk 151 processed | Rows so far: 15,093,449
Chunk 152 processed | Rows so far: 15,193,449
Chunk 153 processed | Rows so far: 15,293,449
Chunk 154 processed | Rows so far: 15,393,449
Chunk 155 processed | Rows so far: 15,493,449
Chunk 156 processed | Rows so far: 15,593,449
Chunk 157 processed | Rows so far: 15,693,449
Chunk 158 processed | Rows so far: 15,793,449
Chunk 159 processed | Rows so far: 15,893,449
Chunk 160 processed | Rows so far: 15,993,449
Chunk 161 processed | Rows so far: 16,093,449
Chunk 162 processed | Rows so far: 16,193,449
Chunk 163 processed | Rows so far: 16,293,449
Chunk 164 processed | Rows so far: 16,305,911
ETL Completed Successfully!
Total rows processed: 16,305,911
Time taken: 4.33 minutes

In [92]:
import pandas as pd

chunksize = 100000

total_rows = 0
missing_counts = None
duplicate_rows = 0
duplicate_complaint_ids = 0
seen_ids = set()

for chunk_number, chunk in enumerate(pd.read_csv(OUTPUT_FILE, chunksize=chunksize), start=1):
    
    total_rows += len(chunk)

    # Missing values
    if missing_counts is None:
        missing_counts = chunk.isnull().sum()
    else:
        missing_counts += chunk.isnull().sum()

    # Duplicate full rows inside chunk
    duplicate_rows += chunk.duplicated().sum()

    # Duplicate complaint IDs across full file
    ids = chunk["complaint_id"].dropna().astype(str)

    duplicate_complaint_ids += ids.isin(seen_ids).sum()
    seen_ids.update(ids)

    print(f"Checked chunk {chunk_number} | Rows checked: {total_rows:,}")

missing_report = pd.DataFrame({
    "Missing Count": missing_counts,
    "Missing %": (missing_counts / total_rows) * 100
})

print("Total Rows:", total_rows)
print("Duplicate Rows:", duplicate_rows)
print("Duplicate Complaint IDs:", duplicate_complaint_ids)

missing_report.sort_values("Missing %", ascending=False)

Checked chunk 1 | Rows checked: 100,000
Checked chunk 2 | Rows checked: 200,000
Checked chunk 3 | Rows checked: 300,000
Checked chunk 4 | Rows checked: 400,000
Checked chunk 5 | Rows checked: 500,000
Checked chunk 6 | Rows checked: 600,000
Checked chunk 7 | Rows checked: 700,000
Checked chunk 8 | Rows checked: 800,000
Checked chunk 9 | Rows checked: 900,000
Checked chunk 10 | Rows checked: 1,000,000
Checked chunk 11 | Rows checked: 1,100,000
Checked chunk 12 | Rows checked: 1,200,000
Checked chunk 13 | Rows checked: 1,300,000
Checked chunk 14 | Rows checked: 1,400,000
Checked chunk 15 | Rows checked: 1,500,000
Checked chunk 16 | Rows checked: 1,600,000
Checked chunk 17 | Rows checked: 1,700,000
Checked chunk 18 | Rows checked: 1,800,000
Checked chunk 19 | Rows checked: 1,900,000
Checked chunk 20 | Rows checked: 2,000,000
Checked chunk 21 | Rows checked: 2,100,000
Checked chunk 22 | Rows checked: 2,200,000
Checked chunk 23 | Rows checked: 2,300,000
Checked chunk 24 | Rows checked: 2,400,000
Checked chunk 25 | Rows checked: 2,500,000
Checked chunk 26 | Rows checked: 2,600,000
Checked chunk 27 | Rows checked: 2,700,000
Checked chunk 28 | Rows checked: 2,800,000
Checked chunk 29 | Rows checked: 2,900,000
Checked chunk 30 | Rows checked: 3,000,000
Checked chunk 31 | Rows checked: 3,100,000
Checked chunk 32 | Rows checked: 3,200,000
Checked chunk 33 | Rows checked: 3,300,000
Checked chunk 34 | Rows checked: 3,400,000
Checked chunk 35 | Rows checked: 3,500,000
Checked chunk 36 | Rows checked: 3,600,000
Checked chunk 37 | Rows checked: 3,700,000
Checked chunk 38 | Rows checked: 3,800,000
Checked chunk 39 | Rows checked: 3,900,000
Checked chunk 40 | Rows checked: 4,000,000
Checked chunk 41 | Rows checked: 4,100,000
Checked chunk 42 | Rows checked: 4,200,000
Checked chunk 43 | Rows checked: 4,300,000
Checked chunk 44 | Rows checked: 4,400,000
Checked chunk 45 | Rows checked: 4,500,000
Checked chunk 46 | Rows checked: 4,600,000
Checked chunk 47 | Rows checked: 4,700,000
Checked chunk 48 | Rows checked: 4,800,000
Checked chunk 49 | Rows checked: 4,900,000
Checked chunk 50 | Rows checked: 5,000,000
Checked chunk 51 | Rows checked: 5,100,000
Checked chunk 52 | Rows checked: 5,200,000
Checked chunk 53 | Rows checked: 5,300,000
Checked chunk 54 | Rows checked: 5,400,000
Checked chunk 55 | Rows checked: 5,500,000
Checked chunk 56 | Rows checked: 5,600,000
Checked chunk 57 | Rows checked: 5,700,000
Checked chunk 58 | Rows checked: 5,800,000
Checked chunk 59 | Rows checked: 5,900,000
Checked chunk 60 | Rows checked: 6,000,000
Checked chunk 61 | Rows checked: 6,100,000
Checked chunk 62 | Rows checked: 6,200,000
Checked chunk 63 | Rows checked: 6,300,000
Checked chunk 64 | Rows checked: 6,400,000
Checked chunk 65 | Rows checked: 6,500,000
Checked chunk 66 | Rows checked: 6,600,000
Checked chunk 67 | Rows checked: 6,700,000
Checked chunk 68 | Rows checked: 6,800,000
Checked chunk 69 | Rows checked: 6,900,000
Checked chunk 70 | Rows checked: 7,000,000
Checked chunk 71 | Rows checked: 7,100,000
Checked chunk 72 | Rows checked: 7,200,000
Checked chunk 73 | Rows checked: 7,300,000
Checked chunk 74 | Rows checked: 7,400,000
Checked chunk 75 | Rows checked: 7,500,000
Checked chunk 76 | Rows checked: 7,600,000
Checked chunk 77 | Rows checked: 7,700,000
Checked chunk 78 | Rows checked: 7,800,000
Checked chunk 79 | Rows checked: 7,900,000
Checked chunk 80 | Rows checked: 8,000,000
Checked chunk 81 | Rows checked: 8,100,000
Checked chunk 82 | Rows checked: 8,200,000
Checked chunk 83 | Rows checked: 8,300,000
Checked chunk 84 | Rows checked: 8,400,000
Checked chunk 85 | Rows checked: 8,500,000
Checked chunk 86 | Rows checked: 8,600,000
Checked chunk 87 | Rows checked: 8,700,000
Checked chunk 88 | Rows checked: 8,800,000
Checked chunk 89 | Rows checked: 8,900,000
Checked chunk 90 | Rows checked: 9,000,000
Checked chunk 91 | Rows checked: 9,100,000
Checked chunk 92 | Rows checked: 9,200,000
Checked chunk 93 | Rows checked: 9,300,000
Checked chunk 94 | Rows checked: 9,400,000
Checked chunk 95 | Rows checked: 9,500,000
Checked chunk 96 | Rows checked: 9,600,000
Checked chunk 97 | Rows checked: 9,700,000
Checked chunk 98 | Rows checked: 9,800,000
Checked chunk 99 | Rows checked: 9,900,000
Checked chunk 100 | Rows checked: 10,000,000
Checked chunk 101 | Rows checked: 10,100,000
Checked chunk 102 | Rows checked: 10,200,000
Checked chunk 103 | Rows checked: 10,300,000
Checked chunk 104 | Rows checked: 10,400,000
Checked chunk 105 | Rows checked: 10,500,000
Checked chunk 106 | Rows checked: 10,600,000
Checked chunk 107 | Rows checked: 10,700,000
Checked chunk 108 | Rows checked: 10,800,000
Checked chunk 109 | Rows checked: 10,900,000
Checked chunk 110 | Rows checked: 11,000,000
Checked chunk 111 | Rows checked: 11,100,000
Checked chunk 112 | Rows checked: 11,200,000
Checked chunk 113 | Rows checked: 11,300,000
Checked chunk 114 | Rows checked: 11,400,000
Checked chunk 115 | Rows checked: 11,500,000
Checked chunk 116 | Rows checked: 11,600,000
Checked chunk 117 | Rows checked: 11,700,000
Checked chunk 118 | Rows checked: 11,800,000
Checked chunk 119 | Rows checked: 11,900,000
Checked chunk 120 | Rows checked: 12,000,000
Checked chunk 121 | Rows checked: 12,100,000
Checked chunk 122 | Rows checked: 12,200,000
Checked chunk 123 | Rows checked: 12,300,000
Checked chunk 124 | Rows checked: 12,400,000
Checked chunk 125 | Rows checked: 12,500,000
Checked chunk 126 | Rows checked: 12,600,000
Checked chunk 127 | Rows checked: 12,700,000
Checked chunk 128 | Rows checked: 12,800,000
Checked chunk 129 | Rows checked: 12,900,000
Checked chunk 130 | Rows checked: 13,000,000
Checked chunk 131 | Rows checked: 13,100,000
Checked chunk 132 | Rows checked: 13,200,000
Checked chunk 133 | Rows checked: 13,300,000
Checked chunk 134 | Rows checked: 13,400,000
Checked chunk 135 | Rows checked: 13,500,000
Checked chunk 136 | Rows checked: 13,600,000
Checked chunk 137 | Rows checked: 13,700,000
Checked chunk 138 | Rows checked: 13,800,000
Checked chunk 139 | Rows checked: 13,900,000
Checked chunk 140 | Rows checked: 14,000,000
Checked chunk 141 | Rows checked: 14,100,000
Checked chunk 142 | Rows checked: 14,200,000
Checked chunk 143 | Rows checked: 14,300,000
Checked chunk 144 | Rows checked: 14,400,000
Checked chunk 145 | Rows checked: 14,500,000
Checked chunk 146 | Rows checked: 14,600,000
Checked chunk 147 | Rows checked: 14,700,000
Checked chunk 148 | Rows checked: 14,800,000
Checked chunk 149 | Rows checked: 14,900,000
Checked chunk 150 | Rows checked: 15,000,000
Checked chunk 151 | Rows checked: 15,100,000
Checked chunk 152 | Rows checked: 15,200,000
Checked chunk 153 | Rows checked: 15,300,000
Checked chunk 154 | Rows checked: 15,400,000
Checked chunk 155 | Rows checked: 15,500,000
Checked chunk 156 | Rows checked: 15,600,000
Checked chunk 157 | Rows checked: 15,700,000
Checked chunk 158 | Rows checked: 15,800,000
Checked chunk 159 | Rows checked: 15,900,000
Checked chunk 160 | Rows checked: 16,000,000
Checked chunk 161 | Rows checked: 16,100,000
Checked chunk 162 | Rows checked: 16,200,000
Checked chunk 163 | Rows checked: 16,300,000
Checked chunk 164 | Rows checked: 16,305,911
Total Rows: 16305911
Duplicate Rows: 0
Duplicate Complaint IDs: 0

                              Missing Count  Missing %
sub_issue                            919473   5.638894
sub_product                          235276   1.442888
company_response_to_consumer         163578   1.003182
state                                 61600   0.377777
date_sent_to_company                  44938   0.275593
date_received                         17084   0.104772
zip_code                               1165   0.007145
issue                                     6   0.000037
complaint_id                              2   0.000012
product                                   0   0.000000
consumer_complaint_narrative              0   0.000000
company_public_response                   0   0.000000
company                                   0   0.000000
tags                                      0   0.000000
submitted_via                             0   0.000000
timely_response                           0   0.000000

In [98]:
cleaned_sample = pd.read_csv(OUTPUT_FILE, nrows=1000, low_memory=False)

cleaned_sample.dtypes

date_received                    object
product                          object
sub_product                      object
issue                            object
sub_issue                        object
consumer_complaint_narrative     object
company_public_response          object
company                          object
state                            object
zip_code                         object
tags                             object
submitted_via                    object
date_sent_to_company             object
company_response_to_consumer     object
timely_response                  object
complaint_id                    float64
dtype: object

In [100]:
import pandas as pd
from pathlib import Path

MYSQL_READY_FILE = PROJECT_PATH / "data" / "processed" / "complaints_mysql_ready.csv"

chunksize = 100000
first_chunk = True
total_rows = 0
removed_rows = 0

for chunk in pd.read_csv(OUTPUT_FILE, chunksize=chunksize, low_memory=False):

    before = len(chunk)

    # remove rows with missing complaint_id
    chunk = chunk.dropna(subset=["complaint_id"])

    # convert complaint_id to integer
    chunk["complaint_id"] = chunk["complaint_id"].astype("int64")

    # convert date columns to MySQL format
    chunk["date_received"] = pd.to_datetime(chunk["date_received"], errors="coerce").dt.strftime("%Y-%m-%d %H:%M:%S")
    chunk["date_sent_to_company"] = pd.to_datetime(chunk["date_sent_to_company"], errors="coerce").dt.strftime("%Y-%m-%d %H:%M:%S")

    removed_rows += before - len(chunk)
    total_rows += len(chunk)

    chunk.to_csv(
        MYSQL_READY_FILE,
        mode="w" if first_chunk else "a",
        header=first_chunk,
        index=False
    )

    first_chunk = False

print("MySQL ready file created")
print("Rows kept:", total_rows)
print("Rows removed:", removed_rows)

MySQL ready file created
Rows kept: 16305909
Rows removed: 2

In [102]:
import pandas as pd

rows = sum(1 for _ in open(MYSQL_READY_FILE, encoding="utf-8")) - 1
print(rows)

27392213

In [104]:
import pandas as pd

row_count = 0

for chunk in pd.read_csv(MYSQL_READY_FILE, chunksize=100000, low_memory=False):
    row_count += len(chunk)

print(row_count)

16305909